GuessTheAnimal.Web/Models/GuessModel.cs
namespace GuessTheAnimal.Web.Models
{
	public class GuessModel
	{
		public string Guess { get; set; }
		public int? NoId { get; set; }
		public int Id { get; set; }

		public bool AppendToYesNode { get { return !NoId.HasValue; } }
	}
}

GuessTheAnimal.Web/Models/NewGuess.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace GuessTheAnimal.Web.Models
{
	public class NewGuess
	{
		[Required(ErrorMessage = "Reikėtų nurodyti klausimą")]
		[DisplayName("Kokį klausimą reikėjo užduoti?")]
		public string Question { get; set; }
		[Required(ErrorMessage = "Reikėtų nurodyti atsakymą")]
		[DisplayName("Koks tai buvo gyvūnas?")]
		public string Guess { get; set; }
		public int? Id { get; set; }
		public byte? AddToYes { get; set; }
	}
}

GuessTheAnimal.Web/Models/QuestionModel.cs
namespace GuessTheAnimal.Web.Models
{
	public class QuestionModel
	{
		public string Question { get; set; }
		public int Id { get; set; }
		public int? NoId { get; set; }
	}
}

GuessTheAnimal.Web/Models/Translators/Translators.cs
using GuessTheAnimal.Web.DA;

namespace GuessTheAnimal.Web.Models.Translators
{
	internal static class Translators
	{
		public static QuestionModel AsQuestion(this Node node)
		{
			return null == node ? null : new QuestionModel {Id = node.Id, NoId = node.NoId, Question = node.Question};
		}

		public static GuessModel AsGuess(this Node node)
		{
			return null == node ? null : new GuessModel {Guess = node.Guess, Id = node.Id, NoId = node.YesId};
		}
	}
}

GuessTheAnimal.Web/Controllers/GameController.cs
using System;
using System.Web.Mvc;
using GuessTheAnimal.Web.Logic;
using GuessTheAnimal.Web.Models;
using GuessTheAnimal.Web.Models.Translators;

namespace GuessTheAnimal.Web.Controllers
{
	public class GameController : Controller
	{
		private readonly IDecisionTree _tree;

		public GameController() : this(new DecisionTree())
		{
		}

		public GameController(IDecisionTree tree)
		{
			_tree = tree;
		}

		//
		// GET: /Game/
		public ActionResult Index()
		{
			return View();
		}
		
		public ActionResult Start()
		{
			var model = _tree.GetNode(null).AsQuestion();

			if (null == model)
				return RedirectToAction("Giveup");

			return View("Ask", model);
		}

		public ActionResult Guess(int id)
		{
			var model = _tree.GetNode(id).AsGuess();
			return View("Guess", model);
		}

		public ActionResult Ask(int id, int? noid)
		{
			if (null == noid)
				return RedirectToAction("Giveup", new{id, toyes = 0});

			var question = _tree.GetNode(noid).AsQuestion();
			return View("Ask", question);
		}

		public ActionResult End()
		{
			return View();
		}

		public ActionResult Giveup(int? id, byte? toyes)
		{
			return View("Giveup", new NewGuess{Id = id, AddToYes = toyes});
		}

		[HttpPost]
		public ActionResult Giveup(NewGuess newGuess)
		{
			// for unit test only :(
			if (String.IsNullOrEmpty(newGuess.Guess)) ModelState.AddModelError("a", "a");

			if (!ModelState.IsValid)
				return View("Giveup", newGuess);

			_tree.AddNode(newGuess.Id, newGuess.AddToYes, newGuess.Question, newGuess.Guess);
			return RedirectToAction("Index");
		}
	}
}

GuessTheAnimal.Web/Views/Game/Ask.cshtml
@model GuessTheAnimal.Web.Models.QuestionModel

<h2>@Model.Question</h2>

@Html.ActionLink("Taip", "Guess", new { id = Model.Id })
@Html.RouteLink("Ne", "Ask", new { id = Model.Id, noid = Model.NoId })

GuessTheAnimal.Web/Views/Game/End.cshtml
<h2>Valio!</h2>
<p class ="lead">Dar kartą?</p>
@Html.ActionLink("Taip", "Start")
@Html.ActionLink("Ne", "Index")

GuessTheAnimal.Web/Views/Game/Giveup.cshtml
@model GuessTheAnimal.Web.Models.NewGuess

<h2>Bijau, kad man tenka pasiduoti :(</h2>
@using (Html.BeginForm())
{
	<fieldset>
		<legend>Gerasis žmogau, padėkite man daugiau sužinoti apie šį pasaulį</legend>
		@Html.LabelFor(l => l.Guess)
		@Html.TextBoxFor(l => l.Guess, new{placeholder = "atsakymas"})
		@Html.ValidationMessageFor(l => l.Guess)

		@Html.LabelFor(l => l.Question)
		@Html.TextBoxFor(l => l.Question, new{placeholder = "klausimas"})
		@Html.ValidationMessageFor(l => l.Question)
		
		@Html.HiddenFor(l=> l.Id)
		@Html.HiddenFor(l=> l.AddToYes)

		<br />

		<input type="submit" value="Prisimink" class="btn btn-primary" />
	</fieldset>
}

GuessTheAnimal.Web/Views/Game/Guess.cshtml
@model GuessTheAnimal.Web.Models.GuessModel

<h2>Spėju</h2>
<div class="alert alert-info">
	Gal tai yra <strong>@Model.Guess</strong>?
</div>

@Html.ActionLink("Taip", "End")
@if (Model.AppendToYesNode)
{
	@Html.RouteLink("Ne", "Append", new { id = Model.Id, toyes = 1 })
}
else
{
	@Html.RouteLink("Ne", "Ask", new { id = Model.Id, noid = Model.NoId })
}

GuessTheAnimal.Web/Views/Game/Index.cshtml
<h2>Pažaiskim?</h2>

<p class="lead">žaidimas labai paprastas: tu sugalvoji gyvūną (bet man nesakai, gerai?), o aš uždavinėsiu klausimus ir bandysiu atspėti, kas tai.</p>

@Html.ActionLink("Pradedam...", "Start")

GuessTheAnimal.Web/Views/Shared/_layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Atspėk gyvūną</title>
	@Styles.Render("~/Content/bootstrap")
</head>
<body>
	<div class="navbar navbar-inverse"> 
		<div class="navbar-inner">
			<ul class="nav">
				<li>
					@Html.ActionLink("Pradžia", "Index", "Game")
				</li>
			</ul>
		</div>
	</div>
	<div class="container">
		@RenderBody()
	</div>
	@Scripts.Render("~/bundles/bootstrap")
	<script type="text/javascript">
		$(document).ready(function() {
			$('.container > a').addClass('btn btn-large btn-primary');
		});
	</script>
</body>
</html>